### PR TITLE
TF Energy update

### PR DESCRIPTION
**Pull request by Prunoideae**
Added soy milk aggregator, a machine to consume fluid, item and energy
to make new items (Mainly soy milk). And recipe api related to this.
Added a highly abstract base class - TileEntityProcessorBase, and its
inventoried version, to make the processing machine pattern more clear.

### CODE REVIEW

**Comment by Prunoideae** [comment]
@pentantan I wrote an example of using TofuForce with items based on the TofuForce Core you done.

**Comment by ghost** [comment]
ooo! thanks!

**Comment by Prunoideae** [comment]
After messing with BakedModel and other things for over an hour, I found it almost impossible to add some rendering both damage bar and the tofu energy bar at the same time without the IItemRenderer which was deprecated in 1.8 for my own limit, then now the problem became harder: what form of energy will the TofuEnergy items show?
At this point I could give out 2 answer:
One is to convert the damage bar into the energy bar, and remove damage mechanism in the TofuForce Core and much more thing.
The other is to use the ItemColorHandler, Like vazkii did to his Mana Tablet.
This could be a serious problem as it decides which path I will write the code next.

**Comment by Prunoideae** [comment]
Wait... I found a solution.

**Pull request merged**
